#!/usr/bin/env python3

from gtts import gTTS

print(f"\033[32m Hi Hello !!!")
print(f"\033[32m It is a Text To Voice Generator Script...")

text = input(f"\033[32m Enter the content : ")

save = input(f"\033[32m Enter the file path, file name & file type ( Mention the file type like : .mp3 ) : ")

tts = gTTS(text=text, lang="en")

tts.save(save)

print(f"\033[32m Voice Audio Saved Successfully !!!")
